### ISSUE TITLE
Forslag til -ere-verb: samlokalisere

### ISSUE THREAD

**Issue by FredrikAugust** [flyrev/ereverb.no#7]
**Hvilket -ere-verb mener du bør legges til?**
Samlokalisere.

**Hvordan vil du definere dette -ere-verbet?**
Lokalisere noe på samme sted.

**Kilde/opphav**
Hvor fant du dette -ere-verbet?
NTNUs beslutning om å flytte flere linjer inn i Realfagsblokka.

**Annet**
Har du noe mer å legge til?
A4 for Onlinere!

**Comment by flyrev** [comment]
Godkjent!

Dersom du ønsker, kan du lage en PR der du legger ordet inn i  [ordlista](https://github.com/flyrev/ereverb.no/edit/master/public/lista.json). Hvis ikke så vil det gjøres av meg etter hvert. :)

**Comment by flyrev** [comment]
Dette bringer oss til 1315 -ere-verb. :)

**Comment by flyrev** [comment]
Tusen takk for bidrag, @FredrikAugust! Ser frem til å få enda flere i fremtiden. :)
